version: "3.5"

services:

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: rentapp
      POSTGRES_DB: rentapp

  redis:
    image: redis:latest
    ports:
      - 6379:6379
  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=rentapp